---
  title: "Group 18"
author: "top"
date: "24 марта 2017 г."
output: html_document
---
  
  Это файл для изучения принципа действия нашего проекта и экспериментов. тут должен быть пройден весь тернистый путь от закачки до выгрузки итоговых весов в портфеле.

1 шаг. Скачивание изначальных данных.

```{r}
library(quantmod) 
library(rusquant) 
library(lubridate)
interval <- 60
d<-Sys.Date()
day(d)=day(d)-(interval*4)
getSymbols(Symbols="SBER", from=d, to = Sys.Date(), src = "Finam", period = "day", auto.assign = TRUE) 
getSymbols(Symbols="TATN", from=d, to = Sys.Date(), src = "Finam", period = "day", auto.assign = TRUE)
getSymbols(Symbols="ROSN", from=d, to = Sys.Date(), src = "Finam", period = "day", auto.assign = TRUE)
getSymbols(Symbols="FEES", from=d, to = Sys.Date(), src = "Finam", period = "day", auto.assign = TRUE) 
getSymbols(Symbols="BANE", from=d, to = Sys.Date(), src = "Finam", period = "day", auto.assign = TRUE) 
getSymbols(Symbols="AFLT", from=d, to = Sys.Date(), src = "Finam", period = "day", auto.assign = TRUE) 
firms <- data.frame(SBER[,4], TATN[,4], ROSN[,4], FEES[,4], BANE[,4], AFLT[,4]) 
head(firms)
```

2 шаг. Подсчет доходностей для каждой из фирм.

```{r}
firms$SBERrho<-c(NA, diff(log(firms$SBER.Close))) 
firms$TATNrho<-c(NA, diff(log(firms$TATN.Close))) 
firms$ROSNrho<-c(NA, diff(log(firms$ROSN.Close))) 
firms$FEESrho<-c(NA, diff(log(firms$FEES.Close))) 
firms$BANErho<-c(NA, diff(log(firms$BANE.Close))) 
firms$AFLTrho<-c(NA, diff(log(firms$AFLT.Close))) 
```

3 шаг. Подсчет плавающего СКО за период.

```{r}
sd30 <- rollapplyr(firms[,7:12], 30, sd, fill=NA) 
```

4 шаг...


